### ISSUE TITLE
Unhandled exception when preprocessing a file that uses #include

### ISSUE THREAD

**Issue by timmartin** [nanonyme/simplecpreprocessor#5]
Whenever I try to preprocess a file that uses `#include`, I get the following exception:

```
Traceback (most recent call last):
  File "preprocess.py", line 4, in <module>
    for line in simplecpreprocessor.preprocess(c_file):
  File "/home/tm3/dev/simplecpreprocessor/simplecpreprocessor.py", line 215, in preprocess
    for line in ret:
  File "/home/tm3/dev/simplecpreprocessor/simplecpreprocessor.py", line 180, in process_include
    f = self.headers.open_header(header)
TypeError: open_header() takes exactly 1 argument (2 given)
```

**Comment by nanonyme** [comment]
Thanks. Fix merged. I guess this is the price of the mocking filesystem. Will need to write some real filesystem tests for header openings (as in, excluding other things of preprocessing) to make sure those codepaths won't break again
